### ISSUE TITLE
【./ai-goat.py --run ctfd 】have error

### ISSUE THREAD

**Issue by yida223** [dhammon/ai-goat#5]
this is good project!
but I ran into a problem.
first:
<img width="532" alt="image" src="https://github.com/dhammon/ai-goat/assets/42206940/26cda83b-1de4-4752-8c6b-29cf804e95c3">

so i change code in runner.py
<img width="606" alt="image" src="https://github.com/dhammon/ai-goat/assets/42206940/63fcff66-5606-4abd-925d-da389922d0b9">

but it's not success
<img width="1477" alt="image" src="https://github.com/dhammon/ai-goat/assets/42206940/bf71bf5a-55f6-4f0e-9f02-8a956f2ed818">

my docker-compose version is: 1.29.2

**Comment by dhammon** [comment]
@yida223 Thank you for your interest in this project!  :D 

I tested on a fresh Ubuntu install and could not reproduce (CTFd loaded fine).  I think this may be caused by a local configuration on your end.  Judging by your first screenshot error, it seems the process running ai-goat.py isn't finding the docker-compose executable.  This https://stackoverflow.com/questions/72446973/unknown-shorthand-flag-d-in-d-docker-compose article shows the same error suggesting similar.  

Confirm docker compose is installed and in your PATH with `which docker-compose`.   From the ai-goat directory, where the docker-compose.yml is located, try running `docker-compose up  ctfd -d`.

**Comment by yida223** [comment]
Thank you for your answer. Still not solved the problem, I will try to change the server environment and try again.
