### ISSUE TITLE
Recomendations to run in VM, tutorial

### ISSUE THREAD

**Issue by spomytkin** [dhammon/ai-goat#8]
0. It's an interesting project, thank you! 

1. I'm trying to figure out if I could somehow tune performance of the challenge process in my environment. Per "Requirements" section "Minimum 16GB system memory with at least 8GB dedicated to the challenge; otherwise LLM responses take too long" I configured VM to use a little above 8G, I was looking at "docker stats" for couple sessions and it shows mem usage well under 6G (most of the time 3-5G) considerable CPU and max IO
![image](https://github.com/user-attachments/assets/4fae17d5-c5f1-4a50-86f5-b11b6bc5ad5d)
VM monitoring also shows plenty of free mem.
Timings from process output below
![image](https://github.com/user-attachments/assets/2d31cacb-3f98-49ee-86e4-22b5abc9eec7)
- please check if it looks normal to you.
I assume there something wrong with configuration and information meant to be accessed in memory used from disk

2.  I’d like to collaborate, maybe join and have a couple ideas I'd like to run by you. Would you be open for quick call to discuss (e.g. WhatsApp\Signal\Skype or phone)?

**Comment by havertz2110** [comment]
hello, i also found out that the llm sometimes takes too long to response, good to see that im not alone here :DD

**Comment by dhammon** [comment]
@spomytkin your block IO is really high likely due to swapping (memory is getting dumped to disk and is much slower).  If you bump the VM to 12 GBs you should see a 90% decrease in time.

Thank you so much for the interest in the project and the contribution with troubleshooting!  I'm on LinkedIn if you want to connect/chat www.linkedin.com/in/daniel-hammon
